export const START_GET_CUSTOMER = "START_GET_CUSTOMER";
export const GET_SUCCESS_CUSTOMER = "GET_SUCCESS_CUSTOMER";
export const GET_FAILED_CUSTOMER = "GET_FAILED_CUSTOMER";
export const START_DELETE_CUSTOMER = "START_DELETE_CUSTOMER";
export const DELETE_SUCCESS_CUSTOMER = "DELETE_SUCCESS_CUSTOMER";
export const DELETE_FAILED_CUSTOMER = "DELETE_FAILED_CUSTOMER";

export default {
  START_GET_CUSTOMER,
  GET_SUCCESS_CUSTOMER,
  GET_FAILED_CUSTOMER,
  START_DELETE_CUSTOMER,
  DELETE_SUCCESS_CUSTOMER,
  DELETE_FAILED_CUSTOMER
};
