export const START_GET_CUSTOMER_PAGE = "START_GET_CUSTOMER_PAGE";
export const GET_SUCCESS_CUSTOMER_PAGE = "GET_SUCCESS_CUSTOMER_PAGE";
export const GET_FAILED_CUSTOMER_PAGE = "GET_FAILED_CUSTOMER_PAGE";
export const DELETE_SUCCESS_CUSTOMER_PAGE = "DELETE_SUCCESS_CUSTOMER_PAGE";
export const DELETE_FAILED_CUSTOMER_PAGE = "DELETE_FAILED_CUSTOMER_PAGE";
export const CHANGE_PAGE_CUSTOMER_PAGE = "CHANGE_PAGE_CUSTOMER_PAGE";

export default {
  START_GET_CUSTOMER_PAGE,
  GET_SUCCESS_CUSTOMER_PAGE,
  GET_FAILED_CUSTOMER_PAGE,
  DELETE_SUCCESS_CUSTOMER_PAGE,
  DELETE_FAILED_CUSTOMER_PAGE,
  CHANGE_PAGE_CUSTOMER_PAGE
};
