export const START_GET_DETAIL_CUSTOMER = "START_GET_DETAIL_CUSTOMER";
export const GET_SUCCESS_DETAIL_CUSTOMER = "GET_SUCCESS_DETAIL_CUSTOMER";
export const GET_FAILED_DETAIL_CUSTOMER = "GET_FAILED_DETAIL_CUSTOMER";
export const CHANGE_PAGE_DETAIL_USER_PAGE = "CHANGE_PAGE_DETAIL_USER_PAGE";
export const DELETE_SUCCESS_DETAIL_CUSTOMER_PAGE =
  "DELETE_SUCCESS_DETAIL_CUSTOMER_PAGE";
export const CHANGE_AVATAR_USER_SUCCESS = "CHANGE_AVATAR_USER_SUCCESS";
export const CHANGE_AVATAR_USER_FAILED = "CHANGE_AVATAR_USER_FAILED";
export const DELETE_AVATAR_USER_SUCCESS = "DELETE_AVATAR_USER_SUCCESS";
export const DELETE_AVATAR_USER_FAILED = "DELETE_AVATAR_USER_FAILED";
export const UPDATE_DETAIL_USER_SUCCESS = "UPDATE_DETAIL_USER_SUCCESS";
export const UPDATE_DETAIL_USER_FAILED = "UPDATE_DETAIL_USER_FAILED";

export default {
  START_GET_DETAIL_CUSTOMER,
  GET_SUCCESS_DETAIL_CUSTOMER,
  GET_FAILED_DETAIL_CUSTOMER,
  CHANGE_PAGE_DETAIL_USER_PAGE,
  DELETE_SUCCESS_DETAIL_CUSTOMER_PAGE,
  CHANGE_AVATAR_USER_SUCCESS,
  CHANGE_AVATAR_USER_FAILED,
  DELETE_AVATAR_USER_SUCCESS,
  DELETE_AVATAR_USER_FAILED,
  UPDATE_DETAIL_USER_SUCCESS,
  UPDATE_DETAIL_USER_FAILED
};
