export const START_GET_DETAIL_CUSTOMER = "START_GET_DETAIL_CUSTOMER";
export const GET_SUCCESS_DETAIL_CUSTOMER = "GET_SUCCESS_DETAIL_CUSTOMER";
export const GET_FAILED_DETAIL_CUSTOMER = "GET_FAILED_DETAIL_CUSTOMER";
export const CHANGE_PAGE_DETAIL_USER_PAGE = "CHANGE_PAGE_DETAIL_USER_PAGE";

export default {
  START_GET_DETAIL_CUSTOMER,
  GET_SUCCESS_DETAIL_CUSTOMER,
  GET_FAILED_DETAIL_CUSTOMER,
  CHANGE_PAGE_DETAIL_USER_PAGE
};
