export const START_GET_CUSTOMER = "START_GET_CUSTOMER";
export const GET_SUCCESS_CUSTOMER = "GET_SUCCESS_CUSTOMER";
export const GET_FAILED_CUSTOMER = "GET_FAILED_CUSTOMER";
export const START_CALL_CUSTOMER = "START_CALL_CUSTOMER";
export const CALL_SUCCESS_CUSTOMER = "CALL_SUCCESS_CUSTOMER";
export const CALL_FAILED_CUSTOMER = "CALL_FAILED_CUSTOMER";

export default {
  START_GET_CUSTOMER,
  GET_SUCCESS_CUSTOMER,
  GET_FAILED_CUSTOMER,
  START_CALL_CUSTOMER,
  CALL_SUCCESS_CUSTOMER,
  CALL_FAILED_CUSTOMER
};
