export const START_GET_PAYER = "START_GET_PAYER";
export const GET_SUCCESS_PAYER = "GET_SUCCESS_PAYER";
export const GET_FAILED_PAYER = "GET_FAILED_PAYER";
export const SELECT_PAYER = "SELECT_PAYER";
export const UPDATE_FORM_DATA = "UPDATE_FORM_DATA";
export const RESET_FORM = "RESET_FORM";
export const SUBMIT_FORM = "SUBMIT_FORM";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";

export default {
  START_GET_PAYER,
  GET_SUCCESS_PAYER,
  GET_FAILED_PAYER,
  SELECT_PAYER,
  SUBMIT_FORM,
  RESET_FORM,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_FAILED,
  CREATE_USER_SUCCESS,
  CREATE_USER_FAILED
};
