export const START_GET_CUSTOMER = "START_GET_CUSTOMER";
export const GET_SUCCESS = "GET_SUCCESS";
export const GET_FAILED = "GET_FAILED";
export const START_CALL = "START_CALL";
export const CALL_SUCCESS = "CALL_SUCCESS";
export const CALL_FAILED = "CALL_FAILED";

export default {
  START_GET_CUSTOMER,
  GET_SUCCESS,
  GET_FAILED,
  START_CALL,
  CALL_SUCCESS,
  CALL_FAILED
};
