export const START_GET_PAYER = "START_GET_PAYER";
export const GET_SUCCESS_PAYER = "GET_SUCCESS_PAYER";
export const GET_FAILED_PAYER = "GET_FAILED_PAYER";
export const SELECT_PAYER = "SELECT_PAYER";
export const UPDATE_FORM_DATA = "UPDATE_FORM_DATA";

export default {
  START_GET_PAYER,
  GET_SUCCESS_PAYER,
  GET_FAILED_PAYER,
  SELECT_PAYER,
  UPDATE_FORM_DATA
};
